name: Android CI

on:
  push:
    branches: 
      - master
      - 'dev'

jobs:
  AndroidSetUp:
    runs-on: ubuntu-latest
    steps:
    # Checkout the branch code
    - uses: actions/checkout@v2
    # Cache and restore the dependencies
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    # Use the JDK Setup
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # Grant permission to Gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # Update Version Code and Version number
    - name: Bump version
      uses: chkfung/android-version-actions@v1.1
      with:
        gradlePath: app/build.gradle
        versionCode: ${{github.run_number}}
        versionName: '1.0.${{github.run_number}}'
  
  BuildDevApp:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
    # Generate Dev APK
    - name: Generate Dev APK
      run: ./gradlew assembleDevRelease
    # Sign APK
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/dev/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEYSTORE_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
  
  BuildProdcutionApp:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    # Generate Production APK
    - name: Generate Production APK
      run: ./gradlew assembleProdRelease
    # Sign APK
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/prod/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEYSTORE_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
  
  ArtifactAPK:  
    runs-on: ubuntu-latest
    steps:
    # Artifact the Generated APK
    - name: Artifact the APK
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: |
          **/*.apk
          **/*.aab
