name: Android CI

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the branch code
    - uses: actions/checkout@v2
    # Cache and restore the dependencies
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    # Use the JDK Setup
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # Grant permission to Gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # Generate Dev APK
    - name: Generate Dev APK
      run: ./gradlew assembleDevRelease
      if: ${{ github.base_ref == "dev" }}
    # Generate Production APK
    - name: Generate Production APK
      run: ./gradlew assembleProdRelease
      if: ${{ github.base_ref == "master" }}
    # Artifact the Generated APK
    - name: Artifact the APK
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          **/*.apk
          **/*.aab
